#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan  3 12:31:35 2018

@author: Callum

THIS IS AN ISING MODEL SIMULATION
"""

import numpy as np
import matplotlib.pyplot as plt
import math as math
import random
